edition: 1.0.0
name: hello-world-app
access: "{{ access }}"
vars: # 全局变量
  region: "cn-hangzhou"


services:
  mysqlCreator: # 业务名称/模块名称
    component: fc
    props:
      region:  ${vars.region}
      service:
        name: "photoview"
        internetAccess: true
        role: "{{ roleArn }}"
        description: "创建MySQL并使用"
        logConfig: auto
      function:
        name:  ${vars.service.name}_creator
        description: "create mysql resource"
        runtime: custom-container
        customContainerConfig:
          image:  registry.cn-hangzhou.aliyuncs.com/serverless_devs/serverless-rds-creator-image:0.0.1
        memorySize: 1024
        timeout: 1800
  photoview:
    component: fc
    actions:
      pre-deploy:
        - plugin: ${path(./plugin)}
          args:
            service_name: ${vars.service.name}
            function_region: ${vars.region}
            function_name: ${vars.service.name}_creator
            oss_bucket: "{{ ossBucket }}"
            oss_object_name: "{{ ossObjectName }}"
            endpoint: rds-data.cn-hangzhou.aliyuncs.com
            databaseName: photoview
    props:
      region: ${vars.region}
      service:
        name: "photoview"
        internetAccess: true
        role: "{{ roleArn }}"
        description: "创建MySQL并使用"
        logConfig: auto
        nasConfig: auto
      function:
        name: ${vars.service.name}_consumer
        description:
        memorySize: 3072
        runtime: custom-container
        timeout: 60
        caPort: 80
        instanceConcurrency: 10
        customContainerConfig:
          image: registry.cn-hangzhou.aliyuncs.com/serverless_dataapi/fc:0.3  #镜像由https://github.com/chengzhengyubian/fc-photoview-code代码构建
          command: '["/app/photoview"]'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS